src/Entity/Fournisseur.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FournisseurRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Fournisseur extends Tiers
{
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }

}

src/Entity/Tiers.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\MappedSuperclass
 */
class Tiers
{
    use TimestampTrait;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_complet;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pays;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telephone;

    public function __toString()
    {
        return (string) $this->nom_complet . "(" . $this->numero .")";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getNomComplet(): ?string
    {
        return $this->nom_complet;
    }

    public function setNomComplet(string $nom_complet): self
    {
        $this->nom_complet = $nom_complet;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(?string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

}

src/Form/FournisseurType.php
<?php

namespace App\Form;

use App\Entity\Fournisseur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FournisseurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('numero')
            ->add('nom_complet')
            ->add('adresse')
            ->add('email')
            ->add('ville')
            ->add('pays')
            ->add('code_postal')
            // ->add('createdAt')
            // ->add('updatedAt')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Fournisseur::class,
        ]);
    }
}

src/Controller/FournisseurController.php
<?php

namespace App\Controller;

use App\Entity\Fournisseur;
use App\Form\FournisseurType;
use App\Repository\FournisseurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/fournisseur")
 */
class FournisseurController extends AbstractController
{
    /**
     * @Route("/", name="fournisseur_index", methods={"GET"})
     */
    public function index(FournisseurRepository $fournisseurRepository): Response
    {
        return $this->render('fournisseur/index.html.twig', [
            'fournisseurs' => $fournisseurRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="fournisseur_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $fournisseur = new Fournisseur();
        $form = $this->createForm(FournisseurType::class, $fournisseur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($fournisseur);
            $entityManager->flush();

            return $this->redirectToRoute('fournisseur_index');
        }

        return $this->render('fournisseur/new.html.twig', [
            'fournisseur' => $fournisseur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="fournisseur_show", methods={"GET"})
     */
    public function show(Fournisseur $fournisseur): Response
    {
        return $this->render('fournisseur/show.html.twig', [
            'fournisseur' => $fournisseur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="fournisseur_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Fournisseur $fournisseur): Response
    {
        $form = $this->createForm(FournisseurType::class, $fournisseur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('fournisseur_index');
        }

        return $this->render('fournisseur/edit.html.twig', [
            'fournisseur' => $fournisseur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="fournisseur_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Fournisseur $fournisseur): Response
    {
        if ($this->isCsrfTokenValid('delete'.$fournisseur->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($fournisseur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('fournisseur_index');
    }
}

templates/fournisseur/_delete_form.html.twig
<form method="post" action="{{ path('fournisseur_delete', {'id': fournisseur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fournisseur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/fournisseur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/fournisseur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Fournisseur{% endblock %}

{% block body %}
    <h1>Edit Fournisseur</h1>

    {{ include('fournisseur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('fournisseur_index') }}">back to list</a>

    {{ include('fournisseur/_delete_form.html.twig') }}
{% endblock %}

templates/fournisseur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fournisseur index{% endblock %}

{% block body %}
    <h1>Fournisseur index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Numero</th>
                <th>Nom_complet</th>
                <th>Adresse</th>
                <th>Email</th>
                <th>Ville</th>
                <th>Pays</th>
                <th>Code_postal</th>
                <th>Id</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fournisseur in fournisseurs %}
            <tr>
                <td>{{ fournisseur.numero }}</td>
                <td>{{ fournisseur.nomComplet }}</td>
                <td>{{ fournisseur.adresse }}</td>
                <td>{{ fournisseur.email }}</td>
                <td>{{ fournisseur.ville }}</td>
                <td>{{ fournisseur.pays }}</td>
                <td>{{ fournisseur.codePostal }}</td>
                <td>{{ fournisseur.id }}</td>
                <td>{{ fournisseur.createdAt ? fournisseur.createdAt|date('Y-m-d H:i:s T') : '' }}</td>
                <td>{{ fournisseur.updatedAt ? fournisseur.updatedAt|date('Y-m-d H:i:s T') : '' }}</td>
                <td>
                    <a href="{{ path('fournisseur_show', {'id': fournisseur.id}) }}">show</a>
                    <a href="{{ path('fournisseur_edit', {'id': fournisseur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('fournisseur_new') }}">Create new</a>
{% endblock %}

templates/fournisseur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Fournisseur{% endblock %}

{% block body %}
    <h1>Create new Fournisseur</h1>

    {{ include('fournisseur/_form.html.twig') }}

    <a href="{{ path('fournisseur_index') }}">back to list</a>
{% endblock %}

templates/fournisseur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fournisseur{% endblock %}

{% block body %}
    <h1>Fournisseur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Numero</th>
                <td>{{ fournisseur.numero }}</td>
            </tr>
            <tr>
                <th>Nom_complet</th>
                <td>{{ fournisseur.nomComplet }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ fournisseur.adresse }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ fournisseur.email }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ fournisseur.ville }}</td>
            </tr>
            <tr>
                <th>Pays</th>
                <td>{{ fournisseur.pays }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ fournisseur.codePostal }}</td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ fournisseur.id }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ fournisseur.createdAt ? fournisseur.createdAt|date('Y-m-d H:i:s T') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ fournisseur.updatedAt ? fournisseur.updatedAt|date('Y-m-d H:i:s T') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('fournisseur_index') }}">back to list</a>

    <a href="{{ path('fournisseur_edit', {'id': fournisseur.id}) }}">edit</a>

    {{ include('fournisseur/_delete_form.html.twig') }}
{% endblock %}